### ISSUE TITLE
Building on windows: locks up on sphinx build to read_config

### ISSUE THREAD

**Issue by nicolan** [Robpol86/sphinxcontrib-versioning#18]
It unpacks the tar for my chosen version and  gets to "partially running sphinx-build to read configuration for: master".

Then it blocks-waiting on **sphinx_.py : read_config**, in the _child.join()_ invocation. (Could this do with a timeout in there to help it clean up after failure?)

From what I can see in the tmp directories, the .doctrees look like they're all made correctly (assuming this is what's meant to happen?). Sphinx reports: sources read 100%.

I realise that it's not returning after the call into the Sphinx api, so not sure how much you can do to fix what's going. Let me know if I can send log files/config/etc to help out.

Same results on Windows native or via cygwin.

**Comment by Robpol86** [comment]
I've got an issue tracking Windows support: https://github.com/Robpol86/sphinxcontrib-versioning/issues/3

**Comment by nicolan** [comment]
Thanks for the quick response. Hit me up if you need testing help!

**Comment by Robpol86** [comment]
I changed a lot of stuff around multiprocessing which involved read_config() in the latest release. Windows is now officially supported. Let me know if you still run into this problem.

Thanks for reporting it.
